Feature AB#12 AB#11 :[Add Auto mapper , Mediatr,StyleCop ]
TunNetCom/TunNetCom-AionTime pull request #1
Opened 2024-03-23 22:43 UTC by MarwenSaad

Feature AB#12 AB#11 :[Add Auto mapper , Mediatr,StyleCop ]

2024-03-24 23:31 UTC, Nieze-BenMansour requested changes

2024-03-24 23:31 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/AutoMapping/MappingProfile.cs
> +            this.CreateMap<OrganizationRequest, Organization>().ReverseMap();
no need for the ReverseMap

2024-03-24 23:31 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/Feature/OrganizationAction/Commands/AddOrganization/AddOrganizationCommandHandler.cs
> +    private readonly IGenericRepository<Organization> organizationRepository = organizationRepository;
IGenericRepository  --> IRepository

2024-03-24 23:31 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/AutoMapping/MappingProfile.cs
> +﻿namespace TunNetCom.AionTime.TimeLogService.Application.AutoMapping
﻿namespace TunNetCom.AionTime.TimeLogService.Application.AutoMapping  --->  ﻿namespace TunNetCom.AionTime.TimeLogService.Application.AutoMapping;

2024-03-24 23:31 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/Feature/OrganizationAction/Commands/AddOrganization/AddOrganizationCommand.cs
> +public record AddOrganizationCommand(OrganizationRequest organizationDTO) : IRequest<int>;
we can't accept a DTO in the command

2024-03-24 23:31 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/Feature/OrganizationAction/Commands/AddOrganization/AddOrganizationCommandHandler.cs
> +        var organization = this.mapper.Map<Organization>(request.organizationDTO);
we need to implement the DDD

2024-03-24 23:31 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/Feature/OrganizationAction/Commands/DeletOrganization/DeleteOrganizationCommandHandler.cs
> +        var organization = this.mapper.Map<Organization>(request.organization);
in the delete we need just the Id

2024-03-24 23:31 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/Feature/OrganizationAction/Queries/GetOrganization/GetOrganizationsQueryHandler.cs
> +﻿using System;
unused usings

2024-03-24 23:31 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/Feature/OrganizationAction/Queries/GetOrganization/GetOrganizationsQueryHandler.cs
> +            var organizations =this.mapper.Map<IReadOnlyList<OrganizationRequest>>(res);
dont forget the spaces

2024-03-24 23:31 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Budget.API/Controllers/TimeLogServiceController.cs
> +
Ya A5I mayjish el controller kolhom yraj3ou ok, check this: 
https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design

2024-03-25 22:34 UTC, MarwenSaad commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/AutoMapping/MappingProfile.cs
> +            this.CreateMap<OrganizationRequest, Organization>().ReverseMap();
I need this for the GetOrganizationHandler to reverse mapping

2024-03-25 22:41 UTC, MarwenSaad commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/Feature/OrganizationAction/Commands/AddOrganization/AddOrganizationCommand.cs
> +public record AddOrganizationCommand(OrganizationRequest organizationDTO) : IRequest<int>;
Entity ?

2024-03-25 22:44 UTC, MarwenSaad commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/Feature/OrganizationAction/Commands/DeletOrganization/DeleteOrganizationCommandHandler.cs
> +        var organization = this.mapper.Map<Organization>(request.organization);
public async Task DeleteAsync(T entity)
{
    _ = this.context.Remove(entity);
    _ = await this.context.SaveChangesAsync();
}

2024-03-25 22:50 UTC, MarwenSaad commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Budget.API/Controllers/TimeLogServiceController.cs
> +
I will implement a global exception handler

2024-03-26 00:20 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/AutoMapping/MappingProfile.cs
> +            this.CreateMap<OrganizationRequest, Organization>().ReverseMap();
use "File scoped namespaces"

2024-03-26 00:20 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/AutoMapping/MappingProfile.cs
> +﻿namespace TunNetCom.AionTime.TimeLogService.Application.AutoMapping
use "File scoped namespaces"

2024-03-26 00:22 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/AutoMapping/MappingProfile.cs
> +            this.CreateMap<OrganizationRequest, Organization>().ReverseMap();
Entites should be made by their parametred constructors

2024-03-26 00:22 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/Feature/OrganizationAction/Commands/AddOrganization/AddOrganizationCommand.cs
> +public record AddOrganizationCommand(OrganizationRequest organizationDTO) : IRequest<int>;
nope parameters

2024-03-26 00:24 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/Feature/OrganizationAction/Commands/DeletOrganization/DeleteOrganizationCommandHandler.cs
> +        var organization = this.mapper.Map<Organization>(request.organization);
bad implementation and remebrer about the soft delete

2024-03-26 00:24 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Budget.API/Controllers/TimeLogServiceController.cs
> +
working with exception will cost us a lot of memory leaks

2024-03-26 00:25 UTC, Nieze-BenMansour commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Budget.API/Controllers/TimeLogServiceController.cs
> +
and we should follow the rest standart

2024-04-06 01:35 UTC, Nieze-BenMansour requested changes

2024-04-07 18:59 UTC, MarwenSaad commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Contracts/CustomProblemDetails/CustomProblemDetails.cs
> +    public IDictionary<string, string> Errors { get; set; } = new Dictionary<string, string>();
the natve one contain only 

 Title = 
 Status =
 Detail = 
 Type =

2024-04-07 18:59 UTC, MarwenSaad commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Budget.API/Middelware/GlobalExceptionHandler.cs
> +        this.logger.LogError(logMessage);
????

2024-04-07 19:12 UTC, MarwenSaad commented on src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Application/Feature/OrganizationAction/Commands/UpdateOrganization/UpdateOrganizationCommandHandler.cs
> +        var organization = this.mapper.Map<Organization>(request.organization);
??

2024-04-12 21:17 UTC, merged